[project]
name = "assets-ngeea-ilamb3"
version = "0.1.0"
description = "ilamb3 assets for NGEE-A benchmarking work on CADES"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ilamb3>=2025.5.20",
]

[tool.uv.sources]
ilamb3 = { path = "../ilamb3", editable = true }
